name: mldatafind
channels:
  - conda-forge
dependencies:
  # python/env dependencies
  - python=3.9
  - pip
  - poetry
  - jsonargparse
  # general GW/auth deps
  - krb5
  - ciecplib
  - requests-gssapi
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  - python-ligo-lw
