name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace 
    steps:
    - uses: actions/checkout@v2

    
    # run the library's tests
    -
      name: run tests
      run: pinto run pytest

  # build the container and push it to this
  # repo's container registry
  push_image:
    name: Push docker image
    needs: test  # only run if tests pass
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}  # only run on push to main
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
